name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # build le fichier apk
      - name: Build avec gradle
        run: cd android && ./gradlew assembleRelease

      - name: Archive APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-artifact
          path: android/app/build/outputs/apk/release/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Generate release date
        id: generate_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./apk

      - name: Deploy using scp with generated RSA private key
        run: |
          ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p 22 "mkdir -p ~/mobile/release_${{ steps.generate_date.outputs.date }}"
          scp -r -i ~/.ssh/id_rsa ./apk/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/mobile/release_${{ steps.generate_date.outputs.date }}